# Generated by Django 3.1.7 on 2021-05-04 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collections',
            name='collection',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='definition',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='word',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
